sudo: required
dist: trusty

os: linux
language: cpp
compiler: gcc

addons:
  apt:
    packages: [ man2html, dos2unix, nsis ]

cache:
  apt: true

matrix:
  fast_finish: true
  include:
    - compiler: ": ARM"
      env: IMAGEROOT=${HOME}/image-arm CHOST=arm-linux-gnueabi CBUILD=x86_64-pc-linux-gnu SCRIPT=generic/build
    - compiler: ": snapshot"
      env: SCRIPT=windows-nsis/build-snapshot
    - compiler: ": complete"
      env: SCRIPT=windows-nsis/build-complete
  exclude:
    - compiler: gcc

install:
    - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list.d/xenial.list
    - echo "deb http://archive.ubuntu.com/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list.d/xenial.list
    - sudo apt-get update
    - sudo apt-get -y install dpkg gcc-mingw-w64

before_script:
    - unset CC; unset CXX

script:
    - $SCRIPT
